DATA:
  train_name: coco
  test_name: default
  train_split: 0
  test_split: default
  data_root: /coco/
  train_list: lists/coco/train.txt
  val_list: lists/coco/val.txt
  num_classes_tr: 2 # Counting background for training
  num_classes_val: 20
  use_split_coco: True
  workers: 2
  image_size: 473
  padding_label: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  scale_min: 0.5
  scale_max: 2.0
  rot_min: -10
  rot_max: 10

  padding: avg
  augmentations: ['resize']
  meta_aug: 1 # 1 means no augmentation
  aug_th: [0.15, 0.30]
  aug_type: 1
  wt_file: 1


TRAIN:
  ckpt_path: checkpoints/
  batch_size: 1      # meta_train batch size
  epochs: 20
  log_freq : 50
  debug: False
  save_models: True
  cls_lr: 0.05
  trans_lr: 0.0025
  scale_lr: 1.0
  mixup: False
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: [40, 70]
  iter_per_epoch: 6000
  adapt_iter: 200

MODEL:
  arch: resnet
  pretrained: False
  bins: [1, 2, 3, 6]
  dropout: 0.1
  m_scale: False
  layers: 50
  bottleneck_dim: 512
  heads: 1
  resume_weights: ./pretrained_models/
  model_dir: model_ckpt

Classifier:
  cls_type: ooooo

EVALUATION:
  shot: 1
  random_shot: False
  episodic: True
  norm_feat: True
  batch_size_val: 100
  manual_seed: 2021
  ckpt_used: best
  test_num: 1000
  FB_param_noise: 0
  smoothing: True
  n_runs: 1

DISTRIBUTED:
  gpus: [0]